#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

#define PORTIO_SENS_EN_PIN       (3U)
#define PORTIO_SENS_EN_PORT      (gpioPortB)

#define PORTIO_STP_DIR_PORT      (gpioPortH)
#define PORTIO_STP_DIR_PIN       (3U)
#define PORTIO_STP_STEP_PORT     (gpioPortH)
#define PORTIO_STP_STEP_PIN      (6U)
#define PORTIO_STP_MS1_PORT      (gpioPortH)
#define PORTIO_STP_MS1_PIN       (1U)
#define PORTIO_STP_MS2_PORT      (gpioPortH)
#define PORTIO_STP_MS2_PIN       (0U)
#define PORTIO_STP_EN_PORT       (gpioPortH)
#define PORTIO_STP_EN_PIN        (2U)

#define PORTIO_LED_PORT       (gpioPortF)
#define PORTIO_LED_PIN        (13U)

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ACMP2]
// [ACMP2]$

// $[ACMP3]
// [ACMP3]$

// $[ADC0]
// [ADC0]$

// $[ADC1]
// [ADC1]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BUTTON]
// [BUTTON]$

// $[CAN0]
// [CAN0]$

// $[CAN1]
// [CAN1]$

// $[CMU]
// [CMU]$

// $[CSEN]
// [CSEN]$

// $[DCDC]
// [DCDC]$

// $[EBI]
// [EBI]$

// $[EMU]
// [EMU]$

// $[ETH]
// [ETH]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2C2]
#define PORTIO_I2C2_SCL_PIN        (5U)
#define PORTIO_I2C2_SCL_PORT       (gpioPortI)
#define PORTIO_I2C2_SCL_LOC        (7U)

#define PORTIO_I2C2_SDA_PIN        (4U)
#define PORTIO_I2C2_SDA_PORT       (gpioPortI)
#define PORTIO_I2C2_SDA_LOC        (7U)

// [I2C2]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LCD]
// [LCD]$

// $[LED]
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LETIMER1]
// [LETIMER1]$

// $[LEUART0]
#define PORTIO_LEUART0_RX_PIN      (5U)
#define PORTIO_LEUART0_RX_PORT     (gpioPortD)
#define PORTIO_LEUART0_RX_LOC      (0U)

#define PORTIO_LEUART0_TX_PIN      (14U)
#define PORTIO_LEUART0_TX_PORT     (gpioPortC)
#define PORTIO_LEUART0_TX_LOC      (5U)

// [LEUART0]$

// $[LEUART1]
#define PORTIO_LEUART1_RX_PIN      (7U)
#define PORTIO_LEUART1_RX_PORT     (gpioPortC)
#define PORTIO_LEUART1_RX_LOC      (0U)

#define PORTIO_LEUART1_TX_PIN      (6U)
#define PORTIO_LEUART1_TX_PORT     (gpioPortC)
#define PORTIO_LEUART1_TX_LOC      (0U)

// [LEUART1]$

// $[LFXO]
// [LFXO]$

// $[PCNT0]
// [PCNT0]$

// $[PCNT1]
// [PCNT1]$

// $[PCNT2]
// [PCNT2]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[QSPI0]
// [QSPI0]$

// $[SDIO]
// [SDIO]$

// $[SERIAL]
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[TIMER2]
// [TIMER2]$

// $[TIMER3]
// [TIMER3]$

// $[TIMER4]
// [TIMER4]$

// $[TIMER5]
// [TIMER5]$

// $[TIMER6]
// [TIMER6]$

// $[UART0]
#define PORTIO_UART0_RX_PIN        (15U)
#define PORTIO_UART0_RX_PORT       (gpioPortC)
#define PORTIO_UART0_RX_LOC        (3U)

#define PORTIO_UART0_TX_PIN        (7U)
#define PORTIO_UART0_TX_PORT       (gpioPortD)
#define PORTIO_UART0_TX_LOC        (6U)

// [UART0]$

// $[UART1]
#define PORTIO_UART1_RX_PIN        (13U)
#define PORTIO_UART1_RX_PORT       (gpioPortC)
#define PORTIO_UART1_RX_LOC        (0U)

#define PORTIO_UART1_TX_PIN        (12U)
#define PORTIO_UART1_TX_PORT       (gpioPortC)
#define PORTIO_UART1_TX_LOC        (0U)

// [UART1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_RX_PIN       (10U)
#define PORTIO_USART0_RX_PORT      (gpioPortC)
#define PORTIO_USART0_RX_LOC       (2U)

#define PORTIO_USART0_TX_PIN       (11U)
#define PORTIO_USART0_TX_PORT      (gpioPortC)
#define PORTIO_USART0_TX_LOC       (2U)

// [USART0]$

// $[USART1]
#define PORTIO_USART1_RX_PIN       (6U)
#define PORTIO_USART1_RX_PORT      (gpioPortD)
#define PORTIO_USART1_RX_LOC       (2U)

#define PORTIO_USART1_TX_PIN       (14U)
#define PORTIO_USART1_TX_PORT      (gpioPortA)
#define PORTIO_USART1_TX_LOC       (6U)

// [USART1]$

// $[USART2]
#define PORTIO_USART2_RX_PIN       (8U)
#define PORTIO_USART2_RX_PORT      (gpioPortA)
#define PORTIO_USART2_RX_LOC       (2U)

#define PORTIO_USART2_TX_PIN       (13U)
#define PORTIO_USART2_TX_PORT      (gpioPortA)
#define PORTIO_USART2_TX_LOC       (3U)

// [USART2]$

// $[USART3]
#define PORTIO_USART3_RX_PIN       (7U)
#define PORTIO_USART3_RX_PORT      (gpioPortG)
#define PORTIO_USART3_RX_LOC       (3U)

#define PORTIO_USART3_TX_PIN       (6U)
#define PORTIO_USART3_TX_PORT      (gpioPortG)
#define PORTIO_USART3_TX_LOC       (3U)

// [USART3]$

// $[USART4]
#define PORTIO_USART4_RX_PIN       (1U)
#define PORTIO_USART4_RX_PORT      (gpioPortI)
#define PORTIO_USART4_RX_LOC       (2U)

#define PORTIO_USART4_TX_PIN       (6U)
#define PORTIO_USART4_TX_PORT      (gpioPortI)
#define PORTIO_USART4_TX_LOC       (3U)

// [USART4]$

// $[USART5]
// [USART5]$

// $[USB]
// [USB]$

// $[VCOM]
// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

// $[WTIMER1]
// [WTIMER1]$

// $[WTIMER2]
// [WTIMER2]$

// $[WTIMER3]
// [WTIMER3]$

#endif /* HAL_CONFIG_H */

