/*******************************************************************************
* (c) Copyright 2011 Actel Corporation.  All rights reserved.
*
*  This is a file generated by the IAR Workbench software project
*  It can be modified by the user and will not be overwritten when
*  the software IDE is run after the first time.
*/

#include "drivers/mss_gpio/mss_gpio.h"
#include "CMSIS/system_m2sxxx.h"
#include "mss_uart.h"

#define logo \
"\n\r \*******************************************\n\r \
         Welcome to SmartFusion2 \n\r \
******************************************* \n\r \n\r"

//static void delay(void);

/*-------------------------------------------------------------------------*/
/**
 * main() function.
 */
int main()
{
  
/*---------------------------------------------------------------
    Initialization and Setup
----------------------------------------------------------------*/

	size_t rx_size;
	uint8_t rx_buff[1];

	MSS_UART_init (&g_mss_uart0,
		MSS_UART_115200_BAUD,
		MSS_UART_DATA_8_BITS | MSS_UART_NO_PARITY | MSS_UART_ONE_STOP_BIT);

	MSS_UART_polled_tx_string(&g_mss_uart0, (const uint8_t *)logo);
	MSS_UART_polled_tx_string(&g_mss_uart0, (const uint8_t *)" Hello, world!! \n\r \n\r");

/*---------------------------------------------------------------
* Infinite loop.
----------------------------------------------------------------*/
	for(;;)
	{
		//uint32_t gpio
	}
}